name: fintab_expense
description: FinTab Expense - offline category-wise budget and expense manager.
publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
